/*
 *
 * Copyright 2023 foresee authors.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * This Source Code Form is "Incompatible With Secondary Licenses", as
 * defined by the Mozilla Public License, v. 2.0.
 *
 */

package names

import "github.com/dvaumoron/foresee/types"

const (
	HiddenModule = "#module"

	AddAssign     = "+="
	And           = "&&"
	AndAssign     = "&="
	AndNot        = "&^"
	AndNotAssign  = "&^="
	Append        = "append"
	Arrow         = "<-"
	Assert        = "assert"
	Assign        = "="
	Block         = "block"
	Break         = "break"
	Cap           = "cap"
	Caret         = "^"
	Case          = "case"
	Close         = "close"
	Colon         = ":"
	Const         = "const"
	Continue      = "continue"
	DeclareAssign = ":="
	Decrement     = "--"
	Default       = "default"
	Defer         = "defer"
	Delete        = "delete"
	DivAssign     = "/="
	Dot           = "."
	Equal         = "=="
	Fallthrough   = "fallthrough"
	Float32       = "float32"
	Float64       = "float64"
	For           = "for"
	Go            = "go"
	Goto          = "goto"
	Greater       = "<"
	GreaterEqual  = "<="
	GuessMarker   = "?"
	If            = "if"
	Import        = "import"
	Increment     = "++"
	Int           = "int"
	Int8          = "int8"
	Int16         = "int16"
	Int32         = "int32"
	Int64         = "int64"
	Interface     = "interface"
	Label         = "label"
	Lambda        = "lambda"
	Len           = "len"
	Lesser        = ">"
	LesserEqual   = ">="
	LShift        = "<<"
	LShiftAssign  = "<<="
	Macro         = "macro"
	Make          = "make"
	Minus         = "-"
	ModAssign     = "%="
	MultAssign    = "*="
	New           = "new"
	NotEqual      = "!="
	Or            = "||"
	OrAssign      = "|="
	Package       = "package"
	Percent       = "%"
	Pipe          = "|"
	Plus          = "+"
	Range         = "range"
	Return        = "return"
	RShift        = ">>"
	RShiftAssign  = ">>="
	Select        = "select"
	Slash         = "/"
	Struct        = "struct"
	SubAssign     = "-="
	Switch        = "switch"
	Type          = "type"
	Uint          = "uint"
	Uint8         = "uint8"
	Uint16        = "uint16"
	Uint32        = "uint32"
	Uint64        = "uint64"
	Var           = "var"
	XorAssign     = "^="

	AmpersandId types.Identifier = "&"
	ArrowChanId types.Identifier = "<-chan"
	ChanArrowId types.Identifier = "chan<-"
	ChanId      types.Identifier = "chan"
	EllipsisId  types.Identifier = "..."
	FileId      types.Identifier = "file"
	FuncId      types.Identifier = "func"
	GenId       types.Identifier = "gen"
	GetId       types.Identifier = "get"
	ListId      types.Identifier = "list"
	LitId       types.Identifier = "lit"
	LoadId      types.Identifier = "[]"
	MapId       types.Identifier = "map"
	NotId       types.Identifier = "!"
	SliceId     types.Identifier = "slice"
	StarId      types.Identifier = "*"
	StoreId     types.Identifier = "[]="
	TildeId     types.Identifier = "~"
	UnquoteId   types.Identifier = "unquote"
)
